//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH03_WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public string AvatarUser { get; set; }
        public int MaDG { get; set; }
        public string MaSP { get; set; }
        public string TenKH { get; set; }
        public string DienThoai { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDG { get; set; }
        public Nullable<int> RatingValue { get; set; }
        public string Anh1 { get; set; }
        public string Anh2 { get; set; }
        public string Anh3 { get; set; }
        public string Anh4 { get; set; }
        public string Anh5 { get; set; }
        public string Video { get; set; }
        public string Email { get; set; }
        public Nullable<int> LuotThich { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
