//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH03_WebBanHang.Models
{
    using System;
    using System.Collections.Generic;

    public partial class KhachHang
    {
        public KhachHang()
        {
            this.DonHangs = new HashSet<DonHang>();
            // this.ThichSPs = new HashSet<ThichSP>();
        }

        public Nullable<int> MaTK { get; set; }
        public string AvatarUser { get; set; }
        public int MaKH { get; set; }
        public string HoTen { get; set; }
        public string DienThoai { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> Diem { get; set; }
        public Nullable<bool> TrangThai { get; set; }

        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual TK TK { get; set; }
        //   public virtual ICollection<ThichSP> ThichSPs { get; set; }
        public ICollection<KhachHang> KhachHangs { get; internal set; } = new HashSet<KhachHang>();


    }
}
