//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH03_WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhom
    {
        public Nhom()
        {
            this.SanPhams = new HashSet<SanPham>();
            this.SanPhams1 = new HashSet<SanPham>();
        }
    
        public string MaNhom { get; set; }
        public string TenNhom { get; set; }
        public string DuongDan { get; set; }
        public string AnhNhom { get; set; }
    
        public virtual ICollection<SanPham> SanPhams { get; set; }
        public virtual ICollection<SanPham> SanPhams1 { get; set; }
    }
}
