//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH03_WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiNhanh
    {
        public ChiNhanh()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public string MaCN { get; set; }
        public string TenCN { get; set; }
        public string DiaChiCN { get; set; }
    
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
