//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH03_WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devvn_xaphuongthitran
    {
        public string xaid { get; set; }
        public string nameXP { get; set; }
        public string typeXP { get; set; }
        public string maqh { get; set; }
    }
}
