//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH03_WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ChiTietDonHangs1 = new HashSet<ChiTietDonHang>();
        }
    
        public Nullable<int> MaTK { get; set; }
        public string MaDH { get; set; }
        public Nullable<int> KH { get; set; }
        public System.DateTime Ngay { get; set; }
        public string DiaChiNN { get; set; }
        public string MaCN { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs1 { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual TK TK { get; set; }
    }
}
