//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH03_WebBanHang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VNlocalEntities : DbContext
    {
        public VNlocalEntities()
            : base("name=VNlocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<devvn_quanhuyen> devvn_quanhuyen { get; set; }
        public DbSet<devvn_tinhthanhpho> devvn_tinhthanhpho { get; set; }
        public DbSet<devvn_xaphuongthitran> devvn_xaphuongthitran { get; set; }
    }
}
